# Provision a service account for AWS API access keys
template:
  type: "http"
  url: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.2.7/IAM/service-account.yaml"
stack_name: "bgrande-nextflow-service-account"
stack_tags:
  Department: "CompOnc"
  Project: "imCORE"
  OwnerEmail: "bruno.grande@sagebase.org"
parameters:
  ManagedPolicyArns: ["arn:aws:iam::aws:policy/AmazonS3FullAccess"]
