# Provision an EC2 instance
template_path: managed-ec2-v6.yaml
stack_name: dgutman-htan-ec2
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "computational oncology"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "HTAN"
  # The resource owner
  OwnerEmail: "dagutman@gmail.com"

  # The following parameters are only examples they are not required.
  # You may omit them if you do not need to override the defaults.

  # (Optional) EC2 instance type, default is "t2.nano" (other available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "m5d.xlarge"
  # (Optional) ID of the base AMI (default: ami-97785bed) (supported distros: AWS linux)
  AMIId: "ami-0de53d8956e8dcf80"      # Amazon Linux 2 AMI (HVM), SSD Volume Type
  # (Optional) EC2 boot volume size in GB, default is 8GB, Max is 1000GB
  VolumeSize: "150"
  # (Optional) Run EC2 in a subnet (default: PrivateSubnet) (valid values: PrivateSubnet or PublicSubnet)
  VpcSubnet: "PublicSubnet"
  # (Optional) Expose a port to incoming traffic (default is no open ports) (valid range: 1-65535)
  OpenPort: "80"

  KeyName: EmoryHTAN-dgutman

  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId

# For CI system (do not change)
hooks:
  after_create:
    - !ec2_notify "{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}"




