# Provision an EC2 instance
template:
  type: "http"
  url: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.3.9/EC2/jc-ec2-linux.j2"
stack_name: "dgutman-htan-new2-ec2"
stack_tags:
  Department: "CompOnc"
  Project: "HTAN"
  OwnerEmail: "bruno.grande@sagebase.org"
  CostCenter: "HTAN-DFCI / 120100"

sceptre_user_data:
  Distro: "ubuntu"     # (valid values: aws, ubuntu) AMIId must match distro
  # (Optional) Expose ports to incoming traffic (default is no open ports) (valid range: 1-65535)
  OpenPorts: ["80","443", "22"]
parameters:
  JcUserId: "bruno.grande@sagebase.org"
  # Default account settings, leave alone unless you plan to override
  VpcName: "sandcastlevpc"
  KeyName: "sandbox"
  # AMIId: "ami-0810a318c4b1243c5"      # https://github.com/Sage-Bionetworks-IT/packer-base-amazonlinux2/releases/tag/v1.0.2
  AMIId: "ami-0447d7789ebc37ae3"    # https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-bionic/releases/tag/v1.0.7

  # Settings have default values but can be overriden. Set the below
  # parameters *only* if you want to override the defaults.

  # (Optional) EC2 instance type, default is "t3.micro" (other available types https://aws.amazon.com/ec2/pricing/on-demand/)
  InstanceType: "i3en.2xlarge"
  # (Optional) EC2 boot volume size in GB, default is 8GB, Max is 1000GB
  VolumeSize: "1000"
  # (Optional) Run EC2 in a subnet (default: PrivateSubnet) (valid values: PrivateSubnet or PublicSubnet)
  VpcSubnet: "PublicSubnet"
  # (Optional) Set true to enable daily backups (default: false)
  # BackupEc2: "true"
  # (Optional) Number of daily backups to keep (default: 7) (valid range: 1-180)
  # SnapshotCount: "14"

  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm "/infra/JcConnectKey"
  JcServiceApiKey: !ssm "/infra/JcServiceApiKey"
  JcSystemsGroupId: !ssm "/infra/JcSystemsGroupId"
