# Provision an EC2 instance
template:
  type: "http"
  url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.4.0/templates/EC2/jc-ec2-linux.j2"
stack_name: "jharker-test"
stack_tags:
  Department: "Platform"
  Project: "Infrastucture"
  OwnerEmail: "joni.harker@sagebase.org"
  CostCenter: "Platform Infrastructure / 990300"

sceptre_user_data:
  Distro: "aws"     # (valid values: aws, ubuntu) AMIId must match distro
  # (Optional) Expose ports to incoming traffic (default is no open ports) (valid range: 1-65535)
  # OpenPorts: ["3838","4151"]
parameters:
  JcUserId: "joni.harker@sagebase.org"

  # Default account settings, leave alone unless you plan to override
  VpcName: "sandcastlevpc"
  KeyName: "jharker-ed25519"
  AMIId: "ami-0cff7528ff583bf9a"      # AWS linux 2 AMI 2.0.20200108 x86_64 HVM gp2

  # Settings have default values but can be overriden. Set the below
  # parameters *only* if you want to override the defaults.

  # (Optional) EC2 instance type, default is "t2.nano" (other available types https://aws.amazon.com/ec2/pricing/on-demand/)
  InstanceType: "t3.small"
  # (Optional) EC2 boot volume size in GB, default is 8GB, Max is 1000GB
  # VolumeSize: "200"
  # (Optional) Run EC2 in a subnet (default: PrivateSubnet) (valid values: PrivateSubnet or PublicSubnet)
  # VpcSubnet: "PublicSubnet"
  # (Optional) Set true to enable daily backups (default: false)
  # BackupEc2: "true"
  # (Optional) Number of daily backups to keep (default: 7) (valid range: 1-180)
  # SnapshotCount: "14"

  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm "/infra/JcConnectKey"
  JcServiceApiKey: !ssm "/infra/JcServiceApiKey"
  JcSystemsGroupId: !ssm "/infra/JcSystemsGroupId"
