# Provision an EC2 instance
template_path: templates/managed-ec2-v4.yaml
stack_name: neurolincs-unique-objects-ec2
parameters:
  # The Sage deparment for this resource
  Department: "SysBio"
  # The Sage project this resource will be used for
  Project: "NeuroLINCS"
  # The resource owner
  OwnerEmail: "kenneth.daily@sagebase.org"
  # EC2 instance type (available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "c5.2xlarge"
  VolumeSize: 750
  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  after_create:
    - !notify_ec2

