# Provision an EC2 instance
template_path: managed-ec2-v5.yaml
stack_name: nf-osi-processing
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "CompOnc"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "NF OSI"
  # The resource owner
  OwnerEmail: "sara.gosline@sagebase.org"
  # (Optional) EC2 instance type, default is "t2.nano" (other available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "t2.2xlarge"
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  after_create:
    - !ec2_notify {{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}
