template_path: remote/managed-ec2-linux-v1.j2
stack_name: trytoprovision
sceptre_user_data:
  Distro: "ubuntu"
parameters:
  Department: "CompOnc"
  Project: "dream"
  OwnerEmail: "thomas.yu@sagebionetworks.org"
  VpcName: "sandcastlevpc"
  KeyName: "sandbox"
  AMIId: "ami-0a313d6098716f372"
  InstanceType: "t2.small"
  VolumeSize: "50"
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-linux-v1.j2 --create-dirs -o templates/remote/managed-ec2-linux-v1.j2"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-linux-v1.j2 --create-dirs -o templates/remote/managed-ec2-linux-v1.j2"
  after_create:
    - !ec2_notify "{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}"
