template_path: remote/managed-ec2-v10.j2
stack_name: wow-this-works
parameters:
  Department: CompOnc
  Project: ntap
  OwnerEmail: thomas.yu@sagebase.org
  VpcName: sandcastlevpc
  KeyName: sandbox
  AMIId: ami-0de53d8956e8dcf80
  InstanceType: t2.xlarge
  VolumeSize: 50
  JcConnectKey: /infra/JcConnectKey
  JcServiceApiKey: /infra/JcServiceApiKey
  JcSystemsGroupId: /infra/JcSystemsGroupId
hooks:
  before_create: curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-v10.j2
    --create-dirs -o templates/remote/managed-ec2-v10.j2
  before_update: curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-v10.j2
    --create-dirs -o templates/remote/managed-ec2-v10.j2
  after_create: '{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}'
