repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
    -   id: yamllint
-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.58.2
    hooks:
    -   id: cfn-python-lint
        files: templates/.*\.(json|yml|yaml)$
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
    -   id: remove-tabs
-   repo: https://github.com/Sage-Bionetworks-IT/pre-commit-provisioner
    rev: v0.0.6
    hooks:
    -   id: compare-stack-and-file-names
    -   id: check-stack-names
