project_code: sage-bionetworks
profile: {{ var.profile | default("default") }}
region: {{ var.region | default("us-east-1") }}
template_bucket_name: bootstrap-awss3cloudformationbucket-z6hnifi9i3p
template_key_prefix: {{ environment_variable.TRAVIS_BRANCH | default("testing") }}
admincentral_cf_bucket: "bootstrap-awss3cloudformationbucket-19qromfd235z9"
# Sender for notification hooks
aws_account_name: Sandbox
aws_account_email: aws.sandbox@sagebase.org
# Provisioner defaults
default_ami: "ami-0080e4c5bc078760e"
default_key_pair: "sandbox"
default_vpc: "sandcastlevpc"
default_win_ami: "ami-02d43577e47e684d9"
default_ubuntu_ami: "ami-0a313d6098716f372"
default_awslinux2_ami: "ami-0de53d8956e8dcf80"
